### ISSUE TITLE
V4 of Intent modules compatability

### ISSUE THREAD

**Issue by jpseini** [IntentArchitect/Support#13]
### Ask a question

Are version 4.* of the Intent modules backwards compatible?

The situation:
We have an existing application - in V3 and V4 of Intent Architect, the Software Factory will run without any issue. 
If all Intent modules are updated to use the latest, some modules (listed below) get updated to version 4.*. This causes the following error to occur in the SF:

```
System.Exception: Error occurred in Template: TFG.Modules.WebApi.Program [System.Collections.Generic.List`1[Intent.Modelers.Services.Api.ServiceModel]]
 ---> System.TypeLoadException: Could not load type 'Intent.Modelers.Services.CQRS.Api.OperationExtensionModelExtensions' from assembly 'Intent.Modules.Modelers.Services.CQRS, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at TFG.Modules.WebApi.Templates.Program.ProgramTemplate.<>c.<TransformText>b__0_0(OperationModel x)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at TFG.Modules.WebApi.Templates.Program.ProgramTemplate.TransformText() in C:\Development\Git\DA\Intent Architect\TFG.Modules\TFG.Modules.WebApi\Templates\Program\ProgramTemplate.tt:line 140
   at Intent.Modules.Common.Templates.IntentTemplateBase.RunTemplate() in /home/vsts/work/1/s/Modules/Intent.Modules.Common/Templates/IntentTemplateBase.cs:line 189
   at Intent.Modules.Common.CSharp.Templates.CSharpTemplateBase`1.RunTemplate() in /home/vsts/work/1/s/Modules/Intent.Modules.Common.CSharp/Templates/CSharpTemplateBase.cs:line 176
   at Intent.SoftwareFactory.Templates.TemplateOutput.GenerateOutput() in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\Templates\Outputs\TemplateOutput.cs:line 31
   --- End of inner exception stack trace ---
   at Intent.SoftwareFactory.Templates.TemplateOutput.GenerateOutput() in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\Templates\Outputs\TemplateOutput.cs:line 35
   at Intent.SoftwareFactory.Engine.OutputFile..ctor(IOutputTarget project, ITemplateOutput templateOutput, IFileLog existingFileInfo, ISoftwareFactoryEventDispatcher eventDispatcher) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\Engine\Output\OutputFile.cs:line 30
   at Intent.SoftwareFactory.ProcessOrchestration.<>c__DisplayClass18_2.<ExecuteTemplates>b__1() in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\ProcessOrchestration.cs:line 385
   at Intent.SoftwareFactory.TaskTracker.StartSubTask(String name, Action action, Nullable`1 subTaskCount) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\ProcessOrchestration.cs:line 468
```

Rolling back the 3 modules in question to the last 3.* version resolves the above error. The modules in question:
- Intent.Metadata.WebApi (3.4.0 works, 4.0.1 results in the above)
- Intent.Modelers.Services.CQRS (3.3.6 works, 4.0.0 results in the above)
- Intent.OutputManager.RoslynWeaver (3.3.9 works, 3.3.10 breaks on the CLI and 4.4.0 results in the above)

Thanks.

**Comment by dandrejvv** [comment]
Hi @jpseini , some of the latest modules are dependent on changes that we introduced in Intent Architect v4 and thus will not work on v3. Would you be able to upgrade to Intent Architect v4?
Upgrading to v4 doesn't perform large scale metadata migrations unless you're running an old version of Intent Architect. Also the modules from v3 should still be compatible even when running under Intent Architect v4.
There is the Services designer that will prompt you that it will make some designer metadata changes when you open it. The Domain designer also has some changes introduced when you open it, though its only a stereotype being applied on a package.
If you have saved those changes, and you want to roll back your modules to a previous version you know have worked, you may want to use git to roll back those designer changes too in your Services and Domain designer.

Please let me know if this helps and whether you are still encountering these issues.

**Comment by garethbaars** [comment]
Hi @jpseini,

Just to add to the above, Module's evolve independently of the Intent Architect client version.

Major version bumps indicate that there are breaking changes with the previous version of the Module.

The Modules that you've mentioned above all have API changes, hence their major version bump.

**Comment by jpseini** [comment]
Thanks for the feedback @garethbaars  and @dandrejvv  - understand 100%.

**Comment by dandrejvv** [comment]
Hi @jpseini.
Glad it was helpful.

If you are looking at updating to v4 of the `Intent.Modelers.Services.CQRS` module (which only runs on Intent Architect v4), you may need to do the following to your custom module:

- Open up your `TFG.Modules.WebApi` module in your IDE and ensure that the `Intent.Modelers.Services.CQRS` dependency is updated to `4.0.0` (for nuget and imodspec).
- Once you're able to compile your module, bump the version (optional) and install it in your Intent Architect application so that it can work alongside the other Intent Architect modules.

This should hopefully get you up and running (for other incompatible custom modules, a similar exercise may need to be done). If you run into any issues feel free to reach out to our support channels to assist.
