### ISSUE TITLE
Adding Swashbuckle to Azure Functions

### ISSUE THREAD

**Issue by mrk007dvt** [IntentArchitect/Support#14]
### What happened?

The Azure functions should receive Open API specifications.

### What version of Intent Architect are you using?

4.0.0

### Additional information

**Registering Template: Intent.Modules.AspNetCore.Templates.Startup.StartupTemplateRegistration (4ms)**

System.Exception: Unable to find output target for template [Intent.AspNetCore.Startup] with role [Startup;App.Startup]. Try reinstalling your Module and ensuring that the Template Output has been placed in a valid output location.
   at Intent.SoftwareFactory.Engine.Runtime.ApplicationManager.RegisterTemplate(String templateId, Func`2 createTemplateInstance) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\Engine\Runtime\ApplicationManager.cs:line 192
   at Intent.Modules.Common.Registrations.SingleFileTemplateRegistration.Register(ITemplateInstanceRegistry registry, IApplication application) in /home/vsts/work/1/s/Modules/Intent.Modules.Common/Registrations/SingleFileTemplateRegistration.cs:line 21
   at Intent.Modules.Common.Registrations.TemplateRegistrationBase.DoRegistration(ITemplateInstanceRegistry registry, IApplication application) in /home/vsts/work/1/s/Modules/Intent.Modules.Common/Registrations/TemplateRegistrationBase.cs:line 37
   at Intent.SoftwareFactory.ProcessOrchestration.<>c__DisplayClass14_0.<RegisterTemplate>b__0() in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\ProcessOrchestration.cs:line 115
   at Intent.SoftwareFactory.TaskTracker.StartSubTask(String name, Action action, Nullable`1 subTaskCount) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\ProcessOrchestration.cs:line 468

**Registering Template: Intent.Modules.AspNetCore.Templates.Program.ProgramTemplateRegistration (0ms)**

System.Exception: Unable to find output target for template [Intent.AspNetCore.Program] with role [Startup;App.Program]. Try reinstalling your Module and ensuring that the Template Output has been placed in a valid output location.
   at Intent.SoftwareFactory.Engine.Runtime.ApplicationManager.RegisterTemplate(String templateId, Func`2 createTemplateInstance) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\Engine\Runtime\ApplicationManager.cs:line 192
   at Intent.Modules.Common.Registrations.SingleFileTemplateRegistration.Register(ITemplateInstanceRegistry registry, IApplication application) in /home/vsts/work/1/s/Modules/Intent.Modules.Common/Registrations/SingleFileTemplateRegistration.cs:line 21
   at Intent.Modules.Common.Registrations.TemplateRegistrationBase.DoRegistration(ITemplateInstanceRegistry registry, IApplication application) in /home/vsts/work/1/s/Modules/Intent.Modules.Common/Registrations/TemplateRegistrationBase.cs:line 37
   at Intent.SoftwareFactory.ProcessOrchestration.<>c__DisplayClass14_0.<RegisterTemplate>b__0() in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\ProcessOrchestration.cs:line 115
   at Intent.SoftwareFactory.TaskTracker.StartSubTask(String name, Action action, Nullable`1 subTaskCount) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\ProcessOrchestration.cs:line 468

**Registering Template: Intent.Modules.AspNetCore.Swashbuckle.Templates.SwashbuckleConfiguration.SwashbuckleConfigurationTemplateRegistration (0ms)**

System.Exception: Unable to find output target for template [Intent.AspNetCore.Swashbuckle.SwashbuckleConfiguration] with role [Distribution.SwashbuckleConfiguration]. Try reinstalling your Module and ensuring that the Template Output has been placed in a valid output location.
   at Intent.SoftwareFactory.Engine.Runtime.ApplicationManager.RegisterTemplate(String templateId, Func`2 createTemplateInstance) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\Engine\Runtime\ApplicationManager.cs:line 192
   at Intent.Modules.Common.Registrations.SingleFileTemplateRegistration.Register(ITemplateInstanceRegistry registry, IApplication application) in /home/vsts/work/1/s/Modules/Intent.Modules.Common/Registrations/SingleFileTemplateRegistration.cs:line 21
   at Intent.Modules.Common.Registrations.TemplateRegistrationBase.DoRegistration(ITemplateInstanceRegistry registry, IApplication application) in /home/vsts/work/1/s/Modules/Intent.Modules.Common/Registrations/TemplateRegistrationBase.cs:line 37
   at Intent.SoftwareFactory.ProcessOrchestration.<>c__DisplayClass14_0.<RegisterTemplate>b__0() in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\ProcessOrchestration.cs:line 115
   at Intent.SoftwareFactory.TaskTracker.StartSubTask(String name, Action action, Nullable`1 subTaskCount) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\ProcessOrchestration.cs:line 468

**Registering Template: Intent.Modules.AspNetCore.Swashbuckle.Templates.AuthorizeCheckOperationFilter.AuthorizeCheckOperationFilterTemplateRegistration (0ms)**

System.Exception: Unable to find output target for template [Intent.AspNetCore.Swashbuckle.AuthorizeCheckOperationFilter] with role [Startup]. Try reinstalling your Module and ensuring that the Template Output has been placed in a valid output location.
   at Intent.SoftwareFactory.Engine.Runtime.ApplicationManager.RegisterTemplate(String templateId, Func`2 createTemplateInstance) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\Engine\Runtime\ApplicationManager.cs:line 192
   at Intent.Modules.Common.Registrations.SingleFileTemplateRegistration.Register(ITemplateInstanceRegistry registry, IApplication application) in /home/vsts/work/1/s/Modules/Intent.Modules.Common/Registrations/SingleFileTemplateRegistration.cs:line 21
   at Intent.Modules.Common.Registrations.TemplateRegistrationBase.DoRegistration(ITemplateInstanceRegistry registry, IApplication application) in /home/vsts/work/1/s/Modules/Intent.Modules.Common/Registrations/TemplateRegistrationBase.cs:line 37
   at Intent.SoftwareFactory.ProcessOrchestration.<>c__DisplayClass14_0.<RegisterTemplate>b__0() in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\ProcessOrchestration.cs:line 115
   at Intent.SoftwareFactory.TaskTracker.StartSubTask(String name, Action action, Nullable`1 subTaskCount) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\ProcessOrchestration.cs:line 468

**Comment by joelsteventurner** [comment]
Hi @mrk007dvt 
From what I can see here, it looks like you’ve installed our `Intent.AspNetCore.Swashbuckle` Module. This particular module is for generating `Swashbuckle` with  ASP.NET core patterns. 
We don’t currently have an Azure Functions Swashbuckle module, but could absolutely create one.
Just for prioritization purposes on our side, is this something you need, and if so, in what kind of time frame?

**Comment by mrk007dvt** [comment]
Thanks.

It's something I will need as most of the Azure Functions I develop get consumed by APIM. There is no urgency but I will need it in the not too distant future.

**Comment by joelsteventurner** [comment]
Great, I'll load it onto our product backlog, get it prioritized and be in contact with you around when you can expect the module.

**Comment by mrk007dvt** [comment]
I removed the Swashbuckle module, however 35 of the 43 templates are erroring.

**Comment by dandrejvv** [comment]
Hi @mrk007dvt.
There may be some dependencies left from the Swashbuckle installation that still tries to insert code for AspNetCore. Please have a look if the `Intent.AspNetCore` module is still left or anything else related to that.

**Comment by dandrejvv** [comment]
Hi @mrk007dvt , were you able to resolve your issue based on my suggestion?

**Comment by joelsteventurner** [comment]
We have published a module to provide Swagger / OpenAPI support for Azure function, namely `Intent.AzureFunctions.OpenApi`.
