### ISSUE TITLE
Build Sample project from version 4.0.1 to 4.0.3

### ISSUE THREAD

**Issue by pigullino1975** [IntentArchitect/Support#59]
### What happened?

When i try to compile a project from version 4.0.1 to 4.0.3 occurred following error:

System.Exception: Unable to find output target for template [Intent.AspNetCore.Swashbuckle.Security.AuthorizeCheckOperationFilter] with role [Startup]. Try reinstalling your Module and ensuring that the Template Output has been placed in a valid output location.
   at Intent.SoftwareFactory.Engine.Runtime.ApplicationManager.RegisterTemplate(String templateId, Func`2 createTemplateInstance) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\Engine\Runtime\ApplicationManager.cs:line 192
   at Intent.Modules.Common.Registrations.SingleFileTemplateRegistration.Register(ITemplateInstanceRegistry registry, IApplication application) in /home/vsts/work/1/s/Modules/Intent.Modules.Common/Registrations/SingleFileTemplateRegistration.cs:line 21
   at Intent.Modules.Common.Registrations.TemplateRegistrationBase.DoRegistration(ITemplateInstanceRegistry registry, IApplication application) in /home/vsts/work/1/s/Modules/Intent.Modules.Common/Registrations/TemplateRegistrationBase.cs:line 37
   at Intent.SoftwareFactory.ProcessOrchestration.<>c__DisplayClass14_0.<RegisterTemplate>b__0() in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\ProcessOrchestration.cs:line 115
   at Intent.SoftwareFactory.TaskTracker.StartSubTask(String name, Action action, Nullable`1 subTaskCount) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\ProcessOrchestration.cs:line 476.

Screenshots:
![image](https://github.com/IntentArchitect/Support/assets/44727413/a2f9be4e-4ffc-476b-affb-9583cf91ba66)

![image](https://github.com/IntentArchitect/Support/assets/44727413/e3992b60-e62e-46c9-9400-f54caadc19e5)

All package are up to date.

Thanks in advance.

### What version of Intent Architect are you using?

4.0.3

**Comment by joelsteventurner** [comment]
Hi @pigullino1975 

The error message is indicating that one of the modules, specifically 'Intent.AspNetCore.Swashbuckle.Security', is not correctly configured in the 'Visual Studio' designer.

A couple of things to try / check.
1) Reinstalling the 'Intent.AspNetCore.Swashbuckle.Security' module, (make sure the Visual Studio designer tab is closed while doing so). 
2) If you open up the 'Visual Studio' designer are there any error messages there?

**Comment by pigullino1975** [comment]
Excelent, solved installing the package.

Great job!
