### ISSUE TITLE
Cannot invoke InsertImportDirectives without registering a delegate provider for it

### ISSUE THREAD

**Issue by nicodenysschen** [IntentArchitect/Support#85]
### Ask a question

We upgraded to the latest version of the IT4 and then updated all packages. We receive the following issue when we try and run the factory.
Note that the NestJS project was also upgraded to Node 20 and there are no audit issues or outdated packages.
 
System.Exception: Error occurred in Template: Intent.NodeJS.NestJS.Authentication.Auth.AuthController []
 ---> System.InvalidOperationException: Cannot invoke InsertImportDirectives without registering a delegate provider for it
   at Intent.Modules.Common.TypeScript.Utils.WeaverProvider.InsertImportDirectives(String existingContent, IReadOnlyCollection`1 imports) in /home/vsts/work/1/s/Modules/Intent.Modules.Common.TypeScript/Utils/WeaverProvider.cs:line 20
   at Intent.Modules.Common.TypeScript.Templates.TypeScriptTemplateBase`1.RunTemplate() in /home/vsts/work/1/s/Modules/Intent.Modules.Common.TypeScript/Templates/TypeScriptTemplateBase.cs:line 200
   at Intent.SoftwareFactory.Templates.TemplateOutput.GenerateOutput() in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\Templates\Outputs\TemplateOutput.cs:line 32
   --- End of inner exception stack trace ---
   at Intent.SoftwareFactory.Templates.TemplateOutput.GenerateOutput() in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\Templates\Outputs\TemplateOutput.cs:line 40
   at Intent.SoftwareFactory.Engine.OutputFile..ctor(IOutputTarget project, ITemplateOutput templateOutput, IFileLog existingFileInfo, ISoftwareFactoryEventDispatcher eventDispatcher, ISolutionContext solutionContext) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\Engine\Output\OutputFile.cs:line 38
   at Intent.SoftwareFactory.SoftwareFactoryProcessOrchestrator.GetOutputFile(ITemplateOutput templateOutput, IFileLog existingFileLog) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\SoftwareFactoryProcessOrchestrator.cs:line 598
   at Intent.SoftwareFactory.SoftwareFactoryProcessOrchestrator.<>c__DisplayClass26_2.<ExecuteTemplates>b__1() in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\SoftwareFactoryProcessOrchestrator.cs:line 576
   at Intent.SoftwareFactory.TaskTracker.StartSubTask(String name, Action action, Nullable`1 subTaskCount) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\TaskTracker.cs:line 73

**Comment by dandrejvv** [comment]
Hi @nicodenysschen 

Apologies for this inconvenience, we're in the process of updating the NodeJS modules based on a core change we made on the `Intent.Common.TypeScript` module and it may have been uploaded too early.

You may choose to downgrade that module to `3.4.3` for the time being or you can install the following module `Intent.Code.Weaving.TypeScript` (1.0.0) as this should resolve your issue.

We are in the process of resolving this.
Please let me know if there is anything else we can assist with.

**Comment by nicodenysschen** [comment]
Hello @dandrejvv 
Thank you for the quick response.
Personanlly I like to go forward so I installed the `Intent.Code.Weaving.TypeScript` (1.0.0) and the Factory Ran successfully.
