### ISSUE TITLE
Error installing Intent.Blazor.HttpClients.Dtos.FluentValidation

### ISSUE THREAD

**Issue by jeanerasmuslife** [IntentArchitect/Support#96]
### What happened?

Installed Intent.Blazor.HttpClients.Dtos.FluentValidation module, now getting the following error while running the software factory:

System.Exception: Unable to find output target for template [Intent.Blazor.FluentValidation.ValidatorProvider] with role [Blazor.Client.Validation.ValidatorProvider]. Try reinstalling your Module and ensuring that the Template Output has been placed in a valid output location.
   at Intent.SoftwareFactory.Engine.Runtime.ApplicationManager.RegisterTemplate(String templateId, Func`2 createTemplateInstance) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\Engine\Runtime\ApplicationManager.cs:line 206
   at Intent.Modules.Common.Registrations.SingleFileTemplateRegistration.Register(ITemplateInstanceRegistry registry, IApplication application) in /home/vsts/work/1/s/Modules/Intent.Modules.Common/Registrations/SingleFileTemplateRegistration.cs:line 25
   at Intent.Modules.Common.Registrations.TemplateRegistrationBase.DoRegistration(ITemplateInstanceRegistry registry, IApplication application) in /home/vsts/work/1/s/Modules/Intent.Modules.Common/Registrations/TemplateRegistrationBase.cs:line 37
   at Intent.SoftwareFactory.SoftwareFactoryProcessOrchestrator.<>c__DisplayClass15_0.<RegisterTemplate>b__0() in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\SoftwareFactoryProcessOrchestrator.cs:line 109
   at Intent.SoftwareFactory.TaskTracker.StartSubTask(String name, Action action, Nullable`1 subTaskCount) in D:\AzureDevOpsAgents\IntentProprietaryRepository\_work\1\s\Intent.IntentArchitect\IntentArchitect.SoftwareFactory\Intent.SoftwareFactory\TaskTracker.cs:line 73

### What version of Intent Architect are you using?

4.3.0-beta.11

**Comment by JonathanLydall** [comment]
Hi @jeanerasmuslife,

Could you try downgrade the `Intent.Blazor.HttpClients.Dtos.FluentValidation` module to `1.2.0-pre.9` to see if that helps?

**Comment by jeanerasmuslife** [comment]
Hi @JonathanLydall 

Still getting the same error.

Regards

**Comment by JonathanLydall** [comment]
Hi @jeanerasmuslife, I'd be happy to look at this together quickly over a call, feel free to reach out to me over Teams.
